/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleappl;

import org.junit.Test;
import static org.junit.Assert.*;
//here should be tests
public class AppTest {
//    @Test public void appHasAGreeting() {
//        App classUnderTest = new App();
//       
//    }
}
